### ISSUE TITLE
Disable memcache by default

### ISSUE THREAD

**Issue by mdbenito** [appliedAI-Initiative/pyDVL#210]
- [ ] Default config is no cache
- [ ] Warn about cache disabled
- [ ] Allow separate installation of deps if that makes sense

**Comment by AnesBenmerzoug** [comment]
I don't think it currently makes sense to install the caching deps as extras since the caching is tied up with the pymemcache. Perhaps once we have an abstract interface for Caching we could then consider doing that.

I don't clearly understand the reasoning behind warning about caching being disabled since it is the default. All users will get a warning for just using the default behaviour. I would find that weird as a user.
