### ISSUE TITLE
Remove unnecessary constraint on Least Core subsidy

### ISSUE THREAD

**Issue by AnesBenmerzoug** [appliedAI-Initiative/pyDVL#294]
The Least Core is defined as:

$$
\begin{array}{lll}
\min e \in \mathbb{R}\\
\text{s.t. } & \sum_{i \in N} x_i = u(N), &\\
& \sum_{i \in S} x_i + e \ge u(S), & \forall S \subset N, S \neq \emptyset
\end{array}
$$

The inequality constraint is only defined on proper, non-empty subsets of the set of all agents/players/data points.

However, in some papers, e.g. [If You Like Shapley Then You’ll Love the Core](http://procaccia.info/wp-content/uploads/2020/12/core.pdf), it is defined on all subsets i.e. $\forall S \subseteq N$ and that implies that the subsidy must be non-negative $e \geq 0$ and that should not be the case.

**Comment by mdbenito** [comment]
This should probably be a flag, in order to be able to properly reproduce the paper

**Comment by AnesBenmerzoug** [comment]
I don't think we should or at least not without comparing both first. 
The constraint $e \ge 0$ is not actually discussed in the paper, it is only present in the authors' code.

**Comment by mdbenito** [comment]
> I don't think we should or at least not without comparing both first.

It's precisely to be able to compare that I propose the flag

> The constraint e≥0 is not actually discussed in the paper, it is only present in the authors' code.

As you say in the issue description, the paper implicitly introduces the constraint by allowing all subsets of N. So it is there. The code enforces it maybe because they don't always sample the whole set N as one of the subsets S. At any rate it is present in the implementation that generates the plots and results in the paper so we should be able to reproduce that.

**Comment by AnesBenmerzoug** [comment]
In their code the specifically skip using the total utility in the lower bound constraints:

![image](https://user-images.githubusercontent.com/27914730/223433050-a7fdf342-8dbc-460d-81c8-dffb10da9078.png)

and they skip the empty subset completely:

![image](https://user-images.githubusercontent.com/27914730/223433502-c52a510e-e359-41b3-a4d3-bcbe564cf3d8.png)

**Comment by mdbenito** [comment]
Skipping the empty subset makes sense because they are fitting a model with that many features. As to why they would not include the grand coalition to form the constraints, but then enforce positivity, I don't understand. Since a feasible solution with non-negativity constraint and a feasible solution with the grand coalition for the lower bounds will both be non-negative, I think we can just do as discussed above and leave a flag to remove the grand coalition from the powerset when generating the constraint matrix.
