### ISSUE TITLE
Consider using functorch for computing the hessian for influence functions

### ISSUE THREAD

**Issue by AnesBenmerzoug** [appliedAI-Initiative/pyDVL#344]
As the title suggests, we should consider using [functorch](https://github.com/pytorch/functorch), a package by the developers of PyTorch that brings [JAX-like](https://github.com/google/jax) composable function transforms to PyTorch, for computing the Hessian for influence functions.

It is for example used in the [hypergrad](https://github.com/moskomule/hypergrad) repository which contains the implementation for the paper [Nystrom Method for Accurate and Scalable Implicit Differentiation]( https://doi.org/10.48550/arXiv.2302.09726) (We already have #343 to implement that method).

Some of the things using it would make easier (according to their readme) are:

- computing per-sample-gradients (or other per-sample quantities)
- efficiently computing Jacobians and Hessians
- efficiently computing batched Jacobians and Hessians

**Comment by schroedk** [comment]
Regarding [this](https://discuss.pytorch.org/t/hvp-w-r-t-model-parameters/83520), you have to do a little work around to make torch.autograd.functional.hvp work for differentiation w.r.t to model parameters. In short, you have to make the model a function of it's parameters, instead of params being an attribute.

I will test the suggested solution.
