### ISSUE TITLE
Remove first element from sum of samplers

### ISSUE THREAD

**Issue by kosmitive** [appliedAI-Initiative/pyDVL#346]
We have defined in all shapley estimators the value 0.0 as the first score. However it is not very sensible to condition on an empty set and we shall rather leave out the first iteration. So we shall transform from 

```python
    while not done(result):
        prev_score = 0.0
        permutation = np.random.permutation(u.data.indices)
        permutation_done = False
        truncation.reset()
        for i, idx in enumerate(permutation):
            if permutation_done:
                score = prev_score
            else:
                score = u(permutation[: i + 1])
            marginal = score - prev_score
            result.update(idx, marginal)
            prev_score = score
            if not permutation_done and truncation(i, score):
                permutation_done = True
```

to 

```python
    while not done(result):
        prev_score = None
        permutation = np.random.permutation(u.data.indices)
        truncation.reset()
        for i, idx in enumerate(permutation):
            if prev_score is not None and truncation(i, score):
                score = prev_score
            else:
                score = u(permutation[: i + 1])
            if prev_score is not None:
                marginal = score - prev_score
                result.update(idx, marginal)
                prev_score = score
```

This has to be adopted for all similiar styled samplers as well.

**Comment by mdbenito** [comment]
Your suggestion doesn't seem to be related to samplers in general but to how one performs the first iteration when working with permutations. Note also that samplers are (for now) only used in the semivalues generalization, not in the "old" code for values (we will merge both eventually).
Now, about the first iteration: the algorithm is to take the set of items _before_ the index of the point being considered, and computing the marginal between that, and the set with the point added. This means that if the index of the point appears first, one computes the marginal wrt. an empty set. One could say that there is indeed a mistake in the code, but it is not that we choose 0.0 as default, but that we don't use the default value of the Scorer. We might want to do:

```python
prev_score = u({})
```

Then we also have a similar hardcoded choice in Utility._utility(), where we always return 0.0 for an empty index set, and to be consistent, we should return `self.scorer.default`. However, this breaks user code, because the previous default value for `scorer.default` was `np.nan`, and not 0.0.
